server:
  servlet:
    context-path: /api
spring:
  flyway:
    baseline-on-migrate: true
    baseline-version: 0
    locations: classpath:db
  h2:
    console:
      enabled: true
      path: '/public/h2-console'
  datasource:
    url: 'jdbc:h2:mem:driveways'
    username: 'sa'
    password: ''
